# Generated by Django 4.0.4 on 2022-04-21 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment', models.AutoField(primary_key=True, serialize=False)),
                ('msg', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image_url', models.ImageField(upload_to='course_images')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='course_videos')),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'episode',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('image_url', models.ImageField(upload_to='topic_images')),
                ('related_cousres', models.ManyToManyField(blank=True, to='courses.course')),
            ],
            options={
                'db_table': 'topic',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('descrption', models.CharField(max_length=255)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('total_length', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episodes', models.ManyToManyField(blank=True, to='courses.episode')),
            ],
            options={
                'db_table': 'section',
            },
        ),
    ]
