# Generated by Django 4.0.4 on 2022-04-26 06:39

import cloudinary.models
import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='image_url',
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='topic_images'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='course_images'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
